.\" man page for applydeltaiso
.\" Copyright (c) 2005 Michael Schroeder <mls@suse.de>
.\" See LICENSE.BSD for license
.TH APPLYDELTAISO 8 "Jul 2009"
.SH NAME
applydeltaiso \- reconstruct an iso from the old iso and the deltaiso

.SH SYNOPSIS
.B applydeltaiso
.I oldiso
.I deltaiso
.I newiso

.SH DESCRIPTION
applydeltaiso applies a deltaiso to
.I oldiso
to re-create
.IR newiso .

When specifying
.IR oldiso ,
you can specify a device (such as /dev/dvd).

.SH SEE ALSO
.BR makedeltaiso (8)

.SH AUTHOR
Michael Schroeder <mls@suse.de>
