.\" man page for makedeltaiso
.\" Copyright (c) 2005 Michael Schroeder <mls@suse.de>
.\" See LICENSE.BSD for license
.TH MAKEDELTAISO 8 "Feb 2005"
.SH NAME
makedeltaiso \- create a deltaiso from two isos

.SH SYNOPSIS
.B makedeltaiso
.I oldiso
.I newiso
.I deltaiso

.SH DESCRIPTION
makedeltaiso creates a deltaiso from two isos.

Do not specify a device (such as /dev/dvd) for either
.I oldiso
or
.IR newiso .

.SH SEE ALSO
.BR applydeltaiso (8)

.SH AUTHOR
Michael Schroeder <mls@suse.de>
